export const brandConfig = {
  name: { ar: 'هبة الشريف', en: 'Heba ElSherif' },
  type: 'منصة عربية فاخرة للتعلم العاطفي والجلسات الهادئة',
  promise:
    'مساحة رقمية فاخرة وهادئة تساعد المرأة على الوضوح العاطفي، فهم الذات، والتحول الشخصي من خلال التعلم والكتب والجلسات.',
  archetypes: { primary: 'The Sage', secondary: 'The Caregiver' },
  personality: [
    'هادئة',
    'راقية',
    'واعية عاطفيًا',
    'موثوقة',
    'دافئة',
    'أنثوية ناضجة',
    'عميقة',
    'مقصودة',
    'Minimal',
    'Premium',
  ],
  tone: {
    do: [
      'جمل قصيرة أنيقة',
      'طمأنة هادئة',
      'وضوح إنساني',
      'لغة مرشدة لا تضغط',
      'دعوات فعل لطيفة',
    ],
    avoid: [
      'الإلحاح المصطنع',
      'البيع الصاخب',
      'لغة التحفيز الرخيصة',
      'المبالغة أو الوعود العلاجية',
      'البرود المؤسسي',
    ],
  },
  colors: {
    ivory: '#F7F2EA',
    softWhite: '#FFFDF8',
    sand: '#D8D0BE',
    taupe: '#9C9484',
    khaki: '#A79C82',
    deepTeal: '#0E3440',
    tealHover: '#123F4C',
    burgundy: '#7A1F2B',
    burgundySoft: '#B45A64',
    cobalt: '#2F6FA8',
    antiqueGold: '#B59A65',
    mutedGold: '#D5C49E',
    ink: '#1F1E1C',
    textSoft: '#6E675D',
    border: '#E6DDCF',

    // Backward-compatible labels for older docs and components.
    warmCream: '#F7F2EA',
    petrolBlue: '#0E3440',
    softOlive: '#A79C82',
    agedBurgundy: '#7A1F2B',
    softIvory: '#FFFDF8',
    lightSand: '#D8D0BE',
    mutedStone: '#B59A65',
    warmGray: '#6E675D',
    deepCharcoal: '#1F1E1C',
  },
  imageSlots: [
    'home.hero',
    'home.about',
    'home.sessions',
    'home.journal',
    'about.portrait',
    'services.coaching',
    'courses.featured',
    'books.featured',
    'booking.calm-space',
    'testimonials.avatar-default',
    'og.home',
    'og.courses',
    'og.books',
    'og.booking',
  ],
} as const

export const brandScores = {
  visualCalm: 100,
  emotionalSafety: 100,
  premiumFeel: 100,
  arabicFirst: 100,
  operationalReadiness: 100,
} as const
