export const BRAND = {
  arName: 'هبة الشريف',
  enName: 'Heba ElSherif',
  tagline: 'رحلة هادئة نحو الوضوح العاطفي',
  description:
    'منصة عربية فاخرة للتحول العاطفي والنمو الشخصي من خلال الدورات، الكتب، والجلسات الفردية.',
} as const

export const COLORS = {
  cream: '#F5F0E7',
  petrol: '#2F6173',
  olive: '#6B724E',
  gold: '#B79B6C',
  burgundy: '#7A2433',
  ivory: '#FAF7F2',
  sand: '#E9E0D2',
  stone: '#C8C1B6',
  warmGray: '#8A837B',
  charcoal: '#2A2A2A',
} as const

export const PUBLIC_NAV_LINKS = [
  { href: '/', label: 'الرئيسية' },
  { href: '/start-here', label: 'ابدئي هنا' },
  { href: '/services', label: 'الخدمات' },
  { href: '/programs', label: 'المسارات' },
  { href: '/courses', label: 'الدورات' },
  { href: '/books', label: 'الكتب' },
  { href: '/booking', label: 'الجلسات' },
  { href: '/articles', label: 'المقالات' },
  { href: '/about', label: 'عن هبة' },
  { href: '/trust-safety', label: 'الثقة' },
] as const

export const DASHBOARD_NAV_LINKS = [
  { href: '/dashboard', label: 'رحلتي' },
  { href: '/dashboard/courses', label: 'دوراتي' },
  { href: '/dashboard/books', label: 'كتبي' },
  { href: '/dashboard/sessions', label: 'جلساتي' },
  { href: '/dashboard/orders', label: 'طلباتي' },
  { href: '/dashboard/profile', label: 'الملف الشخصي' },
] as const

export const ADMIN_NAV_LINKS = [
  { href: '/admin', label: 'لوحة التحكم' },
  { href: '/admin/analytics', label: 'التحليلات' },
  { href: '/admin/settings', label: 'البراند والموقع' },
  { href: '/admin/homepage', label: 'الرئيسية' },
  { href: '/admin/theme', label: 'الثيم' },
  { href: '/admin/content-ops', label: 'تشغيل المحتوى' },
  { href: '/admin/customer-journey', label: 'رحلة العميلة' },
  { href: '/admin/quality', label: 'الجودة' },
  { href: '/admin/automation', label: 'الأتمتة' },
  { href: '/admin/commerce', label: 'التجارة' },
  { href: '/admin/assessment', label: 'اختبار البداية' },
  { href: '/admin/analytics-events', label: 'أحداث القياس' },
  { href: '/admin/media', label: 'الصور والميديا' },
  { href: '/admin/navigation', label: 'القوائم' },
  { href: '/admin/seo', label: 'SEO وGoogle' },
  { href: '/admin/feature-flags', label: 'المميزات' },
  { href: '/admin/ai-guide', label: 'AI Guide' },
  { href: '/admin/courses', label: 'الدورات' },
  { href: '/admin/academy', label: 'استوديو التعلم' },
  { href: '/admin/books', label: 'الكتب' },
  { href: '/admin/content', label: 'المحتوى المحمي' },
  { href: '/admin/uploads', label: 'Google Drive' },
  { href: '/admin/articles', label: 'المقالات' },
  { href: '/admin/faqs', label: 'FAQ' },
  { href: '/admin/bookings', label: 'الحجوزات' },
  { href: '/admin/availability', label: 'التوفر والجلسات' },
  { href: '/admin/calendar', label: 'التقويم' },
  { href: '/admin/orders', label: 'الطلبات' },
  { href: '/admin/payments', label: 'الدفع' },
  { href: '/admin/coupons', label: 'الكوبونات' },
  { href: '/admin/pricing', label: 'التسعير' },
  { href: '/admin/bundles', label: 'الباقات' },
  { href: '/admin/reviews', label: 'التقييمات' },
  { href: '/admin/users', label: 'المستخدمون' },
  { href: '/admin/leads', label: 'Leads' },
  { href: '/admin/notifications', label: 'الإشعارات' },
  { href: '/admin/emails', label: 'البريد' },
  { href: '/admin/integrations', label: 'التكاملات' },
  { href: '/admin/security', label: 'الأمان' },
  { href: '/admin/operations', label: 'التشغيل' },
  { href: '/admin/backups', label: 'النسخ الاحتياطي' },
  { href: '/admin/policies', label: 'السياسات' },
  { href: '/admin/legal', label: 'قانوني متقدم' },
  { href: '/admin/journeys', label: 'المسارات' },
  { href: '/admin/experiments', label: 'التجارب' },
  { href: '/admin/logs', label: 'السجل' },
] as const
